### ISSUE TITLE
Code giving an exception

### ISSUE THREAD

**Issue by rajatnarang94** [ThunderTheodore/BDIndex#1]
Hello,

I tried running this code and it's giving me this exception: selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with css selector 'rect[style=\"opacity: 0; \"]'". I tried to search for the solution a lot but nothing seems to be working. Please help me out!!

Thanks
Rajat

**Comment by ThunderTheodore** [comment]
Uh..It seems that Baidu now requires identification code while login in. I'll try to figure this out:)

**Comment by ThunderTheodore** [comment]
Try these new codes. You're supposed to check out the ./login.png and then input the verification code in the console.

**Comment by rajatnarang17** [comment]
Thanks for replying, I'm still getting the same error. And most of the time the verification code doesn't work also. Somehow, I reached till the main chart page, but the code doesn't seem to work on that too.
Will be nice of you , if you could please check once.

**Comment by ThunderTheodore** [comment]
The code runs well for me. So you can successfully login in but fail to capture the graph? What version of phantomjs do you use?

**Comment by rajatnarang17** [comment]
Yes, even before you made this change to incorporate verification code I was able to log in, it gave me the exception mentioned above. I downloaded the latest version of phantomJS, 2.1.

**Comment by ThunderTheodore** [comment]
I have noticed that there are some differences between phantomjs1.9.0 (which i used before) and phantomjs2.1.1. Try the new code:)

**Comment by rajatnarang17** [comment]
Hey, Thanks a lot. I progressed but this time getting the following error, I guess its again a version issue. I think it would be great if you could make something like a config file which specifies the version of python-packages used. Traceback:

Please check out the login.png and input the verification code!
BJXV
Login successfully...
Successfully captured graph...
Successfully captured time span...
Successfully captured scale...
Successfully recognized graph...
Traceback (most recent call last):
  File "/home/rajat/work/BDIndex/main.py", line 19, in <module>
    result = bir.obtain_baidu_index()
  File "/home/rajat/work/BDIndex/baidu_index/img_recog.py", line 30, in obtain_baidu_index
    self.**recog_scale()
  File "/home/rajat/work/BDIndex/baidu_index/img_recog.py", line 55, in __recog_scale
    scale_str = pytesseract.image_to_string(img_scale)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 161, in image_to_string
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ThunderTheodore** [comment]
Did you install tesseract-ocr?
http://stackoverflow.com/questions/28741563/pytesseract-no-such-file-or-directory-error

**Comment by rajatnarang17** [comment]
It's working now, Thanks a lot man, you rock!!
